### PR TITLE
Fix /unmute not checking if the target is muted

### LINKED ISSUE #142: /unmute doesn't check if the target is muted
### Description

Using /unmute will produce successful feedback even if the target is neither role-muted or timed-out

### Reproduction Steps

1. Use /unmute on any non-muted member you have permissions to interact with
2. See that the bot successfully "unmuted" that member even though they weren't muted

### Expected behavior

An error will be returned by the bot saying that the member isn't muted

### Actual behavior

Successful feedback is returned

### Known Workarounds

_Not relevant_

### Configuration

_Not relevant_

### Other information

_Not relevant_

### PR DESCRIPTION
**Pull request by mctaylors**
Closes #142

### CODE REVIEW

File: src/Commands/MuteCommandGroup.cs [hunk 1]
```diff
@@ -315,58 +309,37 @@ var interactionResult
             return await _feedback.SendContextualEmbedResultAsync(failedEmbed, ct);
         }
 
-        var memberData = data.GetOrCreateMemberData(target.ID);
-        var unmuteResult = await _guildApi.ModifyGuildMemberAsync(
-            guildId, target.ID, roles: memberData.Roles.ConvertAll(r => r.ToSnowflake()),
-            reason: $"({user.GetTag()}) {reason}".EncodeHeader(), ct: ct);
-        memberData.MutedUntil = null;
-        if (!unmuteResult.IsSuccess)
+        var guildMemberResult = await _guildApi.GetGuildMemberAsync(guildId, user.ID, ct);
```
Comment (Octol1ttle) [inline src/Commands/MuteCommandGroup.cs:312]: Wrong ID is being used

**Review by Octol1ttle — CHANGES_REQUESTED** [review]

File: src/Commands/MuteCommandGroup.cs [hunk 2]
```diff
@@ -315,58 +309,37 @@ var interactionResult
...
+                reason: $"({user.GetTag()}) {reason}".EncodeHeader(), ct: ct);
+            memberData.MutedUntil = null;
+        }
+
+        if (communicationDisabledUntil is not null)
         {
-            return Result.FromError(unmuteResult.Error);
+            await _guildApi.ModifyGuildMemberAsync(
+                guildId, target.ID, reason: $"({user.GetTag()}) {reason}".EncodeHeader(),
+                communicationDisabledUntil: null, ct: ct);
```
Comment (Octol1ttle) [inline src/Commands/MuteCommandGroup.cs:342]: If the request fails, the user will receive successful feedback anyway

File: src/Commands/MuteCommandGroup.cs [hunk 3]
```diff
@@ -341,47 +357,39 @@ var interactionResult
...
 
-        var embed = new EmbedBuilder().WithSmallTitle(
-                string.Format(Messages.UserUnmuted, target.GetTag()), target)
-            .WithColour(ColorsList.Green).Build();
-
-        return await _feedback.SendContextualEmbedResultAsync(embed, ct);
+        var muteResult = await _guildApi.ModifyGuildMemberAsync(
+            guildId, target.ID, reason: $"({user.GetTag()}) {reason}".EncodeHeader(),
+            communicationDisabledUntil: null, ct: ct);
+        return !muteResult.IsSuccess ? Result.FromError(muteResult.Error) : Result.FromSuccess();
```
Comment (Octol1ttle) [inline src/Commands/MuteCommandGroup.cs:393]: can't you just `return muteResult;`

File: src/Commands/MuteCommandGroup.cs [hunk 4]
```diff
@@ -341,47 +357,39 @@ var interactionResult
...
-            return Result.FromError(unmuteResult.Error);
-        }
+        memberData.MutedUntil = null;
 
-        var title = string.Format(Messages.UserUnmuted, target.GetTag());
-        var description = $"- {string.Format(Messages.DescriptionActionReason, reason)}";
-        var logResult = _utility.LogActionAsync(
-            data.Settings, channelId, user, title, description, target, ColorsList.Green, ct: ct);
-        if (!logResult.IsSuccess)
+        return Result.FromSuccess();
```
Comment (Octol1ttle) [inline src/Commands/MuteCommandGroup.cs:378]: can't you just `if (success) MutedUntil = null; return unmuteResult;`

**Review by Octol1ttle — APPROVED** [review]
