### PR TITLE
Unload guild datas when they become unavailable

### LINKED ISSUE #120: The bot will try to tick guilds even after it has left the server
### Description

If the bot leaves a guild (e.g. it gets kicked), it will still try to tick it's Guild- and MemberData, causing the console to be flooded with errors

### Reproduction Steps

1. Add the bot to a server
2. Kick the bot from that server
3. Monitor the logs

### Expected behavior

The bot will stop ticking these guilds

### Actual behavior

The bot continues to try and tick these guilds

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mctaylors**
Closes #120

### CODE REVIEW

**Review by Octol1ttle — CHANGES_REQUESTED** [review]
We use update services when we have to do something we aren't able to do using just Discord events, which usually involves complex data storage and processing. The issue at hand does not involve any of this.

Unloaded guilds will never have their data loaded because there will be no callers to their data. This means that the only situation we need to handle is the guild becoming unavailable (not just because the bot was kicked!) on runtime. Luckily for us, Discord fires an event that is *exactly* what we need - `GuildDelete` (`IGuildDelete` in Remora).

That means we do not need an extra unnecessary service constantly making requests and consuming CPU time, we just need a responder for the aforementioned event

File: src/Responders/GuildUnloadedResponder.cs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    {
+        _guildData = guildData;
+        _logger = logger;
+    }
+
+    public async Task<Result> RespondAsync(IGuildDelete gatewayEvent, CancellationToken ct = default)
+    {
+        var guildId = gatewayEvent.ID;
+        await _guildData.RemoveGuildId(guildId);
+        _logger.LogInformation("Left guild {guildId}", guildId);
```
Comment (Octol1ttle) [inline src/Responders/GuildUnloadedResponder.cs:31]: image
weird that the build passed

File: src/Responders/GuildUnloadedResponder.cs [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+using Octobot.Data;
+using Octobot.Services;
+using Remora.Discord.API.Abstractions.Gateway.Events;
+using Remora.Discord.Gateway.Responders;
+using Remora.Results;
+
+namespace Octobot.Responders;
+
+/// <summary>
+///     Handles removing guild ID from <see cref="GuildData" /> if bot leaves the guild.
```
Comment (Octol1ttle) [inline src/Responders/GuildUnloadedResponder.cs:12]:
```suggestion
///     Handles removing guild ID from <see cref="GuildData" /> if the guild becomes unavailable.
```

File: src/Services/GuildDataService.cs [hunk 3]
```diff
@@ -142,4 +142,9 @@ public ICollection<Snowflake> GetGuildIds()
     {
         return _datas.Keys;
     }
+
+    public Task RemoveGuildId(Snowflake id)
+    {
+        return Task.FromResult(_datas.TryRemove(id, out _));
+    }
```
Comment (Octol1ttle) [inline src/Services/GuildDataService.cs:149]: 1) This does not need a Task since no asynchronous operations are being performed
2) This should probably return a boolean (since TryRemove also returns a boolean) which should be checked in GuildUnloaded

**Review by Octol1ttle — CHANGES_REQUESTED** [review]

File: src/Responders/GuildUnloadedResponder.cs (hunk 1 above)
Comment (mctaylors) [reply src/Responders/GuildUnloadedResponder.cs:31]: image
my Rider says that everything is ok...

File: src/Responders/GuildUnloadedResponder.cs [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+        GuildDataService guildData, ILogger<GuildUnloadedResponder> logger)
+    {
+        _guildData = guildData;
+        _logger = logger;
+    }
+
+    public Task<Result> RespondAsync(IGuildDelete gatewayEvent, CancellationToken ct = default)
+    {
+        var guildId = gatewayEvent.ID;
+        var removeGuildSucceed = _guildData.RemoveGuildId(guildId);
```
Comment (Octol1ttle) [inline src/Responders/GuildUnloadedResponder.cs:30]: how about `dataRemoved`? (or `isDataRemoved` if you want)

File: src/Services/GuildDataService.cs [hunk 5]
```diff
@@ -142,4 +142,9 @@ public ICollection<Snowflake> GetGuildIds()
     {
         return _datas.Keys;
     }
+
+    public bool RemoveGuildId(Snowflake id)
```
Comment (Octol1ttle) [inline src/Services/GuildDataService.cs:146]: `UnloadGuildData` is probably a more descriptive name

**Review by Octol1ttle — APPROVED** [review]
